'use strict';
const express=require('express');
const helmet=require('helmet');
const rateLimit=require('express-rate-limit');
const {spawn}=require('child_process');
const fs=require('fs');const fsp=fs.promises;const os=require('os');const path=require('path');
const app=express();const PORT=process.env.PORT||3000;const MAX_DOWNLOAD_MB=Number(process.env.MAX_DOWNLOAD_MB||250);const YTDLP=process.env.YTDLP_PATH||'yt-dlp';
app.disable('x-powered-by');
app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'},contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'",'data:','https:'],connectSrc:["'self'"],fontSrc:["'self'",'data:'],objectSrc:["'none'"],baseUri:["'self'"],frameAncestors:["'none'"],formAction:["'self'"]}}}));
app.use(express.json({limit:'20kb'}));app.use(express.urlencoded({extended:false,limit:'20kb'}));
app.use('/api',rateLimit({windowMs:60*60*1000,limit:60,standardHeaders:'draft-8',legacyHeaders:false,message:{error:'Too many requests. Please try again later.'}}));
app.use(express.static(path.join(__dirname,'public'),{extensions:['html']}));
function validateReelUrl(value){try{const u=new URL(value);const host=u.hostname.toLowerCase().replace(/^www\./,'');if(host!=='instagram.com'||!/^\/(reel|reels)\/[A-Za-z0-9_-]+\/?/.test(u.pathname))return null;u.hash='';return u.toString()}catch{return null}}
function runYtDlp(args,timeoutMs=55000){return new Promise((resolve,reject)=>{const proc=spawn(YTDLP,args,{windowsHide:true,env:{...process.env,LC_ALL:'C.UTF-8'}});let stdout='',stderr='';const timer=setTimeout(()=>{proc.kill('SIGKILL');const e=new Error('Request timed out.');e.stderr=stderr;reject(e)},timeoutMs);proc.stdout.on('data',c=>stdout+=c.toString());proc.stderr.on('data',c=>stderr+=c.toString());proc.on('error',err=>{clearTimeout(timer);err.stderr=stderr;reject(err)});proc.on('close',code=>{clearTimeout(timer);if(code===0)resolve({stdout,stderr});else{const e=new Error(stderr.trim()||`yt-dlp exited with code ${code}`);e.stderr=stderr;e.code=code;reject(e)}})})}
function commonArgs(){return['--no-playlist','--no-warnings','--no-call-home','--socket-timeout','18','--retries','2','--extractor-retries','2','--force-ipv4','--user-agent','Mozilla/5.0 (Linux; Android 15; Pixel 9 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Mobile Safari/537.36','--referer','https://www.instagram.com/']}
async function extractJson(reelUrl){
  const attempts=[
    [...commonArgs(),'--impersonate','chrome','--dump-single-json',reelUrl],
    [...commonArgs(),'--dump-single-json',reelUrl]
  ];
  let lastErr;
  for(const args of attempts){try{const out=await runYtDlp(args);return{data:JSON.parse(out.stdout),method:args.includes('--impersonate')?'browser-like request':'standard request'}}catch(e){lastErr=e}}
  throw lastErr;
}
function classifyUpstream(err){const s=String(err?.stderr||err?.message||'').toLowerCase();if(s.includes('login required')||s.includes('rate-limit')||s.includes('rate limit')||s.includes('challenge')||s.includes('requested content is not available'))return'UPSTREAM_BLOCKED';return'EXTRACTION_FAILED'}
app.get('/api/health',async(req,res)=>{let ytdlp='unknown';try{const {stdout}=await runYtDlp(['--version'],7000);ytdlp=stdout.trim()}catch{}res.json({ok:true,service:'instakuku',mode:'public-reels-only',ytdlp})});
app.post('/api/analyze',async(req,res)=>{const reelUrl=validateReelUrl(req.body?.url||'');if(!reelUrl)return res.status(400).json({code:'INVALID_URL',error:'Please enter a valid public Instagram Reel URL.'});try{const {data,method}=await extractJson(reelUrl);const progressive=(data.formats||[]).filter(f=>f.url&&f.vcodec&&f.vcodec!=='none'&&f.acodec&&f.acodec!=='none').map(f=>({formatId:String(f.format_id),ext:f.ext||'mp4',width:f.width||null,height:f.height||null,filesize:f.filesize||f.filesize_approx||null,fps:f.fps||null,note:f.format_note||null})).sort((a,b)=>(b.height||0)-(a.height||0));const seen=new Set();const formats=progressive.filter(item=>{const key=`${item.height||0}-${item.ext}`;if(seen.has(key))return false;seen.add(key);return true}).slice(0,6);res.json({id:data.id||null,title:(data.title||'Instagram Reel').slice(0,180),thumbnail:data.thumbnail||null,duration:data.duration||null,uploader:data.uploader||data.channel||null,formats,method})}catch(err){const code=classifyUpstream(err);res.status(code==='UPSTREAM_BLOCKED'?503:422).json({code,error:code==='UPSTREAM_BLOCKED'?'Instagram blocked the server request for this Reel. Try again later.':'Could not read this public Reel right now.',detail:process.env.DEBUG==='true'?String(err.stderr||err.message).slice(0,1200):undefined})}});
app.get('/api/download',async(req,res)=>{const reelUrl=validateReelUrl(req.query.url||'');if(!reelUrl)return res.status(400).json({error:'Invalid Reel URL.'});const formatId=String(req.query.format||'best').replace(/[^A-Za-z0-9._+-]/g,'');const tmpDir=await fsp.mkdtemp(path.join(os.tmpdir(),'instakuku-'));const outputTpl=path.join(tmpDir,'reel.%(ext)s');try{const selector=formatId==='best'?'best[ext=mp4][vcodec!=none][acodec!=none]/best[vcodec!=none][acodec!=none]':`${formatId}/best[ext=mp4][vcodec!=none][acodec!=none]`;const args=[...commonArgs(),'--impersonate','chrome','--max-filesize',`${MAX_DOWNLOAD_MB}M`,'-f',selector,'--restrict-filenames','-o',outputTpl,reelUrl];try{await runYtDlp(args,180000)}catch(e){await runYtDlp(args.filter((v,i,a)=>!(v==='--impersonate'||a[i-1]==='--impersonate')),180000)}const files=(await fsp.readdir(tmpDir)).filter(n=>!n.endsWith('.part'));if(!files.length)throw new Error('No output file produced.');const filePath=path.join(tmpDir,files[0]);const stat=await fsp.stat(filePath);if(stat.size>MAX_DOWNLOAD_MB*1024*1024)throw new Error('File exceeds server limit.');res.download(filePath,`instakuku-reel-${Date.now()}${path.extname(filePath)||'.mp4'}`,async()=>{await fsp.rm(tmpDir,{recursive:true,force:true}).catch(()=>{})})}catch(err){await fsp.rm(tmpDir,{recursive:true,force:true}).catch(()=>{});if(!res.headersSent)res.status(422).json({error:'Download could not be prepared. Instagram may be rate-limiting the server or the selected format may no longer be available.'})}});
app.use((req,res)=>res.status(404).sendFile(path.join(__dirname,'public','404.html')));
app.listen(PORT,'0.0.0.0',()=>console.log(`InstaKuku running on http://localhost:${PORT}`));
